# Generated by Django 5.2.3 on 2025-09-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], max_length=1, null=True)),
                ('agemax', models.PositiveIntegerField(blank=True, null=True)),
                ('agemin', models.PositiveIntegerField(blank=True, null=True)),
                ('other_requirements', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('is_online', models.BooleanField(blank=True, null=True)),
                ('is_remote', models.BooleanField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, default=list)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_min', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_max', models.CharField(blank=True, max_length=100, null=True)),
                ('deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Temporary', 'Temporary')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('posted_date', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_level', models.CharField(choices=[('Entry', 'Entry'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Director', 'Director'), ('Intern', 'Intern')], max_length=20)),
                ('degree_required', models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Diploma', 'Diploma'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=20, null=True)),
                ('cgpa', models.FloatField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('application_method', models.CharField(choices=[('Online', 'Online'), ('In-person', 'In-person'), ('Email', 'Email'), ('Phone', 'Phone')], max_length=20)),
                ('application_instructions', models.TextField(blank=True, null=True)),
                ('application_url', models.URLField(blank=True, null=True)),
                ('number_of_positions', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('job_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
