# Generated by Django 5.2.3 on 2025-09-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_method',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('In-person', 'In-person'), ('Email', 'Email'), ('Phone', 'Phone')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Entry', 'Entry'), ('Mid', 'Mid'), ('Senior', 'Senior'), ('Director', 'Director'), ('Intern', 'Intern')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship'), ('Temporary', 'Temporary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
